version: '3.9'

services:
  backend:
    image: gabrielnavas/aws-api:v1.0.0
    container_name: aws-sbackend
    ports:
      - "8080:8080" # opcional, só se quiser acessar do host
    networks:
      - app-network

  frontend:
    image: gabrielnavas/aws-web:v1.0.0
    container_name: aws-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
